# spring:
#   security:
#     oauth2:
#       client:
#         registration:
#           google:
#             clientId: 525771635584-jvjkjjuo1s1g49fic6crsn91o943ls4u.apps.googleusercontent.com
#             clientSecret: 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



# server:
#   port: 8080